import { randomUUID } from "crypto";
import { prisma } from "@/lib/prisma";
import { BotRuntimeManager } from "@/lib/bot-runtime";
import { redactSensitiveText } from "@/lib/security";

export const MAX_AUTOMATION_DEPTH = 10;
export const automationTriggers = ["BOT_START","BOT_ONLINE","BOT_OFFLINE","BOT_RECONNECT","BOT_ERROR","BOT_KICKED","CHAT_MESSAGE","PLAYER_JOIN","PLAYER_LEAVE","AUTH_REQUIRED","AUTH_SUCCESS","AUTH_FAILED","COMMAND_EXECUTED","COMMAND_FAILED","SCHEDULE"] as const;
export const automationActions = ["SEND_CHAT","EXECUTE_COMMAND","SEND_NOTIFICATION","DELAY","START_BOT","STOP_BOT","RESTART_BOT"] as const;
export type AutomationContext = { serverId:string; userId?:string; type:string; payload:Record<string,unknown>; chainId?:string; depth?:number; source?:string };
const queue:Array<()=>Promise<void>>=[]; let active=0; const CONCURRENCY=10;
function drain(){while(active<CONCURRENCY&&queue.length){active++; void queue.shift()!().catch(()=>undefined).finally(()=>{active--;drain();});}}
function enqueue(job:()=>Promise<void>){queue.push(job);drain();}
export function matches(actual:unknown, operator:string, expected:string){const value=String(actual??"");switch(operator){case "equals":return value===expected;case "not_equals":return value!==expected;case "contains":return value.includes(expected);case "not_contains":return !value.includes(expected);case "starts_with":return value.startsWith(expected);case "ends_with":return value.endsWith(expected);case "greater_than":return Number(value)>Number(expected);case "less_than":return Number(value)<Number(expected);default:return false;}}
export function placeholder(value:string, context:AutomationContext, server:{name:string;host:string}, status:string){const values:Record<string,string>={"{{message}}":String(context.payload.message??""),"{{player.name}}":String(context.payload.playerName??""),"{{player.uuid}}":String(context.payload.playerUuid??""),"{{server.name}}":server.name,"{{server.ip}}":server.host,"{{server.onlinePlayers}}":String(context.payload.onlinePlayers??""),"{{bot.status}}":status,"{{event.type}}":context.type,"{{event.reason}}":String(context.payload.reason??""),"{{command}}":String(context.payload.command??"")};return Object.entries(values).reduce((result,[key,val])=>result.split(key).join(val),value);}
function field(context:AutomationContext,name:string,status:string){return ({...context.payload,eventType:context.type,botStatus:status,serverStatus:context.payload.serverStatus,onlinePlayers:context.payload.onlinePlayers,ping:context.payload.ping,version:context.payload.version,kickReason:context.payload.reason,authStatus:context.payload.authStatus,playerName:context.payload.playerName,message:context.payload.message,command:context.payload.command} as Record<string,unknown>)[name];}
export async function runAutomation(id:string, context:AutomationContext){const automation=await prisma.automation.findUnique({where:{id},include:{conditions:{orderBy:{position:"asc"}},actions:{orderBy:{position:"asc"}},server:true}});if(!automation||!automation.enabled)return;const depth=context.depth??0;if(depth>=MAX_AUTOMATION_DEPTH)return;const status=(await prisma.botRuntime.findUnique({where:{serverId:context.serverId}}))?.status??"OFFLINE";if(!automation.conditions.every(condition=>matches(field(context,condition.field,status),condition.operator,condition.value)))return;if(automation.executionLimit!==null&&automation.executionCount>=automation.executionLimit)return;if(automation.cooldownSeconds>0&&automation.lastRunAt&&Date.now()-automation.lastRunAt.getTime()<automation.cooldownSeconds*1000)return;const execution=await prisma.automationExecution.create({data:{automationId:id,serverId:context.serverId,chainId:context.chainId??randomUUID(),depth,trigger:context.type,source:context.source??"EVENT",status:"QUEUED"}});enqueue(async()=>{await prisma.automationExecution.update({where:{id:execution.id},data:{status:"RUNNING",startedAt:new Date()}});const results:string[]=[];try{const manager=new BotRuntimeManager();for(const action of automation.actions){const value=action.value?placeholder(action.value,context,automation.server,status):"";if(action.type==="DELAY")await new Promise(resolve=>setTimeout(resolve,Math.min(action.delayMs||0,60000)));else if(action.type==="SEND_CHAT")await manager.sendChat(context.serverId,value);else if(action.type==="EXECUTE_COMMAND")await manager.sendCommand(context.serverId,value);else if(action.type==="SEND_NOTIFICATION")await prisma.notification.create({data:{userId:automation.server.userId,serverId:context.serverId,type:"AUTOMATION",title:automation.name,message:redactSensitiveText(value)}});else if(action.type==="START_BOT")await manager.startBot(context.serverId);else if(action.type==="STOP_BOT")await manager.stopBot(context.serverId);else if(action.type==="RESTART_BOT")await manager.restartBot(context.serverId);results.push(action.type);}await prisma.automation.update({where:{id},data:{executionCount:{increment:1},lastRunAt:new Date()}});await prisma.automationExecution.update({where:{id:execution.id},data:{status:"SUCCESS",finishedAt:new Date(),actions:JSON.stringify(results)}});}catch(error){await prisma.automationExecution.update({where:{id:execution.id},data:{status:"FAILED",finishedAt:new Date(),error:redactSensitiveText(error instanceof Error?error.message:"Automation failed")}});}});}
export async function handleAutomationEvent(context:AutomationContext){const automations=await prisma.automation.findMany({where:{serverId:context.serverId,trigger:context.type,enabled:true},select:{id:true}});for(const automation of automations)await runAutomation(automation.id,context).catch(()=>undefined);}
