import { randomUUID } from "crypto";
import { prisma } from "@/lib/prisma";
import { BotRuntimeManager } from "@/lib/bot-runtime";
import { redactSensitiveText } from "@/lib/security";
export const MAX_AUTOMATION_DEPTH=10;
export const automationTriggers=["BOT_START","BOT_ONLINE","BOT_OFFLINE","BOT_RECONNECT","BOT_ERROR","BOT_KICKED","CHAT_MESSAGE","PLAYER_JOIN","PLAYER_LEAVE","AUTH_REQUIRED","AUTH_SUCCESS","AUTH_FAILED","COMMAND_EXECUTED","COMMAND_FAILED","SCHEDULE"] as const;
export const automationActions=["SEND_CHAT","EXECUTE_COMMAND","SEND_NOTIFICATION","DELAY","START_BOT","STOP_BOT","RESTART_BOT"] as const;
export type AutomationContext={serverId:string;userId?:string;type:string;payload:Record<string,unknown>;chainId?:string;depth?:number;source?:string};
const queue:Array<()=>Promise<void>>=[];let active=0;const CONCURRENCY=10;function drain(){while(active<CONCURRENCY&&queue.length){active++;void queue.shift()!().catch(()=>undefined).finally(()=>{active--;drain();});}}function enqueue(job:()=>Promise<void>){queue.push(job);drain();}
export function placeholder(value:string,c:AutomationContext,s:{name:string;host:string},status:string){const map:Record<string,string>={"{{message}}":String(c.payload.message??""),"{{player.name}}":String(c.payload.playerName??""),"{{player.uuid}}":String(c.payload.playerUuid??""),"{{server.name}}":s.name,"{{server.ip}}":s.host,"{{server.onlinePlayers}}":String(c.payload.onlinePlayers??""),"{{bot.status}}":status,"{{event.type}}":c.type,"{{event.reason}}":String(c.payload.reason??""),"{{command}}":String(c.payload.command??"")};return Object.entries(map).reduce((out,[k,v])=>out.split(k).join(v),value);}
export function matches(actual:unknown,op:string,expected:string){const a=String(actual??"");switch(op){case"equals":return a===expected;case"not_equals":return a!==expected;case"contains":return a.includes(expected);case"not_contains":return !a.includes(expected);case"starts_with":return a.startsWith(expected);case"ends_with":return a.endsWith(expected);case"greater_than":return Number(a)>Number(expected);case"less_than":return Number(a)<Number(expected);default:return false;}}
function value(c:AutomationContext,f:string,status:string){return ({...c.payload,eventType:c.type,botStatus:status,serverStatus:c.payload.serverStatus,onlinePlayers:c.payload.onlinePlayers,ping:c.payload.ping,version:c.payload.version,kickReason:c.payload.reason,authStatus:c.payload.authStatus,playerName:c.payload.playerName,message:c.payload.message,command:c.payload.command} as Record<string,unknown>)[f];}
export async function runAutomation(id:string,c:AutomationContext){const a=await prisma.automation.findUnique({where:{id},include:{conditions:{orderBy:{position:"asc"}},actions:{orderBy:{position:"asc"}},server:true}});if(!a||!a.enabled)return;const depth=c.depth??0;if(depth>=MAX_AUTOMATION_DEPTH)return;const status=(await prisma.botRuntime.findUnique({where:{serverId:c.serverId}}))?.status??"OFFLINE";if(!a.conditions.every(x=>matches(value(c,x.field,status),x.operator,x.value)))return;if(a.executionLimit!==null&&a.executionCount>=a.executionLimit)return;if(a.cooldownSeconds&&a.lastRunAt&&Date.now()-a.lastRunAt.getTime()<a.cooldownSeconds*1000)return;const e=await prisma.automationExecution.create({data:{automationId:id,serverId:c.serverId,chainId:c.chainId??randomUUID(),depth,trigger:c.type,source:c.source??"EVENT",status:"QUEUED"}});enqueue(async()=>{await prisma.automationExecution.update({where:{id:e.id},data:{status:"RUNNING",startedAt:new Date()}});const result:string[]=[];try{const m=new BotRuntimeManager();for(const x of a.actions){const v=x.value?placeholder(x.value,c,a.server,status):"";if(x.delayMs)await new Promise(r=>setTimeout(r,Math.min(x.delayMs,60000)));if(x.type==="SEND_CHAT")await m.sendChat(c.serverId,v);else if(x.type==="EXECUTE_COMMAND")await m.sendCommand(c.serverId,v);else if(x.type==="SEND_NOTIFICATION")await prisma.notification.create({data:{userId:a.server.userId,serverId:c.serverId,type:"AUTOMATION",title:a.name,message:redactSensitiveText(v)}});else if(x.type==="START_BOT")await m.startBot(c.serverId);else if(x.type==="STOP_BOT")await m.stopBot(c.serverId);else if(x.type==="RESTART_BOT")await m.restartBot(c.serverId);result.push(x.type);}await prisma.automation.update({where:{id},data:{executionCount:{increment:1},lastRunAt:new Date()}});await prisma.automationExecution.update({where:{id:e.id},data:{status:"SUCCESS",finishedAt:new Date(),actions:JSON.stringify(result)}});}catch(err){await prisma.automationExecution.update({where:{id:e.id},data:{status:"FAILED",finishedAt:new Date(),error:redactSensitiveText(err instanceof Error?err.message:"Automation failed")}});}});}
export async function handleAutomationEvent(c:AutomationContext){const rows=await prisma.automation.findMany({where:{serverId:c.serverId,trigger:c.type,enabled:true},select:{id:true}});for(const r of rows)await runAutomation(r.id,c).catch(()=>undefined);}
