import { randomUUID } from "crypto";
import { prisma } from "@/lib/prisma";
import { BotRuntimeManager } from "@/lib/bot-runtime";
import { redactSensitiveText } from "@/lib/security";

export const MAX_AUTOMATION_DEPTH = 10;
export const automationTriggers = ["BOT_START","BOT_ONLINE","BOT_OFFLINE","BOT_RECONNECT","BOT_ERROR","BOT_KICKED","CHAT_MESSAGE","PLAYER_JOIN","PLAYER_LEAVE","AUTH_REQUIRED","AUTH_SUCCESS","AUTH_FAILED","COMMAND_EXECUTED","COMMAND_FAILED","SCHEDULE"] as const;
export const automationActions = ["SEND_CHAT","EXECUTE_COMMAND","SEND_NOTIFICATION","DELAY","START_BOT","STOP_BOT","RESTART_BOT"] as const;

export type AutomationContext = { serverId:string; userId?:string; type:string; payload:Record<string,unknown>; chainId?:string; depth?:number };
const queue: (() => Promise<void>)[] = []; let active = 0; const CONCURRENCY = 10;
function enqueue(job:()=>Promise<void>) { queue.push(job); drain(); }
function drain() { while(active < CONCURRENCY && queue.length) { const job=queue.shift()!; active++; job().catch(()=>undefined).finally(()=>{active--;drain();}); } }
export function placeholder(value:string, ctx:AutomationContext, server:{name:string;host:string}, status:string) { const p:Record<string,string>={"{{message}}":String(ctx.payload.message??""),"{{player.name}}":String(ctx.payload.playerName??""),"{{player.uuid}}":String(ctx.payload.playerUuid??""),"{{server.name}}":server.name,"{{server.ip}}":server.host,"{{server.onlinePlayers}}":String(ctx.payload.onlinePlayers??""),"{{bot.status}}":status,"{{event.type}}":ctx.type,"{{event.reason}}":String(ctx.payload.reason??""),"{{command}}":String(ctx.payload.command??"")}; return Object.entries(p).reduce((out,[key,val])=>out.split(key).join(val),value); }
function compare(actual:unknown, operator:string, expected:string) { const a=String(actual??""); const e=expected; switch(operator){case"equals":return a===e;case"not_equals":return a!==e;case"contains":return a.includes(e);case"not_contains":return !a.includes(e);case"starts_with":return a.startsWith(e);case"ends_with":return a.endsWith(e);case"greater_than":return Number(a)>Number(e);case"less_than":return Number(a)<Number(e);default:return false;} }
function field(ctx:AutomationContext, name:string, status:string) { const map:Record<string,unknown>={...ctx.payload,eventType:ctx.type,botStatus:status,serverStatus:ctx.payload.serverStatus,onlinePlayers:ctx.payload.onlinePlayers,ping:ctx.payload.ping,version:ctx.payload.version,kickReason:ctx.payload.reason,authStatus:ctx.payload.authStatus,playerName:ctx.payload.playerName,message:ctx.payload.message,command:ctx.payload.command}; return map[name]; }
export async function runAutomation(automationId:string, ctx:AutomationContext) { const automation=await prisma.automation.findUnique({where:{id:automationId},include:{conditions:{orderBy:{position:"asc"}},actions:{orderBy:{position:"asc"}},server:true}}); if(!automation||!automation.enabled)return;
 const depth=ctx.depth??0; if(depth>=MAX_AUTOMATION_DEPTH)return; const status=(await prisma.botRuntime.findUnique({where:{serverId:ctx.serverId}}))?.status??"OFFLINE"; if(!automation.conditions.every(c=>compare(field(ctx,c.field,status),c.operator,c.value)))return;
 if(automation.executionLimit!==null&&automation.executionCount>=automation.executionLimit)return; if(automation.cooldownSeconds>0&&automation.lastRunAt&&Date.now()-automation.lastRunAt.getTime()<automation.cooldownSeconds*1000)return;
 const execution=await prisma.automationExecution.create({data:{automationId,serverId:ctx.serverId,chainId:ctx.chainId??randomUUID(),depth,trigger:ctx.type,status:"QUEUED"}}); enqueue(async()=>{const started=new Date(); await prisma.automationExecution.update({where:{id:execution.id},data:{status:"RUNNING",startedAt:started}}); const results:string[]=[]; try { const manager=new BotRuntimeManager(); for(const action of automation.actions){const value=action.value?placeholder(action.value,ctx,automation.server,status):""; if(action.delayMs)await new Promise(r=>setTimeout(r,Math.min(action.delayMs,60000))); if(action.type==="SEND_CHAT")await manager.sendChat(ctx.serverId,value); else if(action.type==="EXECUTE_COMMAND")await manager.sendCommand(ctx.serverId,value); else if(action.type==="START_BOT")await manager.startBot(ctx.serverId); else if(action.type==="STOP_BOT")await manager.stopBot(ctx.serverId); else if(action.type==="RESTART_BOT")await manager.restartBot(ctx.serverId); else if(action.type==="SEND_NOTIFICATION")await prisma.notification.create({data:{userId:automation.server.userId,serverId:ctx.serverId,type:"AUTOMATION",title:automation.name,message:redactSensitiveText(value)}}); results.push(action.type); } await prisma.automation.update({where:{id:automationId},data:{executionCount:{increment:1},lastRunAt:new Date()}}); await prisma.automationExecution.update({where:{id:execution.id},data:{status:"SUCCESS",finishedAt:new Date(),actions:JSON.stringify(results)}}); } catch(error) { await prisma.automationExecution.update({where:{id:execution.id},data:{status:"FAILED",finishedAt:new Date(),error:redactSensitiveText(error instanceof Error?error.message:"Automation failed")}}); } }); }
export async function handleAutomationEvent(ctx:AutomationContext) { const automations=await prisma.automation.findMany({where:{serverId:ctx.serverId,trigger:ctx.type,enabled:true},select:{id:true}}); for(const a of automations)runAutomation(a.id,ctx).catch(()=>undefined); }
