import "@/lib/automation/listener";
import mineflayer from "mineflayer";
import { prisma } from "@/lib/prisma";
import { publishEvent } from "@/lib/events";
import { registerRuntime } from "@/lib/bot-runtime";
import { redactSensitiveText } from "@/lib/security";
const serverId=process.env.BOT_SERVER_ID;const runtimeId=process.env.BOT_RUNTIME_ID;if(!serverId||!runtimeId)throw new Error("BOT_SERVER_ID and BOT_RUNTIME_ID are required");
let stopping=false;let retries=0;let bot:ReturnType<typeof mineflayer.createBot>|undefined;
async function log(level:string,event:string,message:string){await prisma.botLog.create({data:{serverId,runtimeId,level,event,message:redactSensitiveText(message)}}).catch(()=>undefined);}
async function state(status:string,error?:string){await prisma.botRuntime.updateMany({where:{serverId,runtimeId},data:{status,state:status,lastHeartbeat:new Date(),lastError:error??null}});}
async function run(){const server=await prisma.server.findFirst({where:{id:serverId,runtime:{runtimeId}}});if(!server)throw new Error("Runtime validation failed");await state("CONNECTING");await log("info","BOT_START",`Connecting to ${server.host}:${server.port}`);bot=mineflayer.createBot({host:server.host,port:server.port,username:server.username,version:server.version==="AUTO"?false:server.version,auth:"offline"});registerRuntime(serverId,{child:process,runtimeId,chat:(message:string)=>bot?.chat(message),command:(command:string)=>bot?.chat(command.startsWith("/")?command:`/${command}`)} as never);bot.once("login",async()=>{await state("ONLINE");await log("info","BOT_ONLINE","Bot is online");await publishEvent({serverId,runtimeId,type:"BOT_ONLINE",userId:server.userId,title:"Bot online",message:`${server.name} is online`});retries=0;});bot.on("chat",async(player,message)=>{await prisma.chatMessage.create({data:{serverId,runtimeId,player,message}}).catch(()=>undefined);await publishEvent({serverId,runtimeId,type:"CHAT_MESSAGE",payload:{playerName:player,message}});});bot.on("end",async()=>{const current=await prisma.botRuntime.findUnique({where:{serverId}});if(stopping||current?.manualStop){await state("OFFLINE");process.exit(0);}if(!server.autoReconnect||retries>=server.maxRetries){await state("ERROR","Reconnect limit reached");process.exit(1);}retries++;await state("RECONNECTING");setTimeout(()=>void run().catch(()=>process.exit(1)),Math.min(server.retryDelay*1000*2**(retries-1),600000));});}
process.on("SIGTERM",async()=>{stopping=true;await state("STOPPING");bot?.quit("Stopped");setTimeout(()=>process.exit(0),1000);});void run().catch(async e=>{await state("ERROR",String(e));process.exit(1);});
