import mineflayer from "mineflayer";
import { prisma } from "@/lib/prisma";
import { redactSensitiveText } from "@/lib/security";
import { publishEvent } from "@/lib/events";
import { registerRuntime } from "@/lib/bot-runtime";
const serverId = process.env.BOT_SERVER_ID; const runtimeId = process.env.BOT_RUNTIME_ID;
if (!serverId || !runtimeId) throw new Error("BOT_SERVER_ID and BOT_RUNTIME_ID are required");
let stopping = false; let retries = 0; let bot: ReturnType<typeof mineflayer.createBot> | undefined;
async function write(level: string, event: string, message: string, meta: Record<string, unknown> = {}) { await prisma.botLog.create({ data: { serverId, runtimeId, level, event, message: redactSensitiveText(message), meta: JSON.stringify(meta) } }).catch(() => undefined); }
async function state(status: string, error?: string) { await prisma.botRuntime.updateMany({ where: { serverId, runtimeId }, data: { status, state: status, lastHeartbeat: new Date(), lastError: error ?? null } }); }
async function run() { const server = await prisma.server.findFirst({ where: { id: serverId, runtime: { runtimeId } } }); if (!server) throw new Error("Runtime ownership validation failed"); await state("CONNECTING"); await write("info", "BOT_START", `Connecting to ${server.host}:${server.port}.`); await publishEvent({ serverId, runtimeId, type: "BOT_START", userId: server.userId, title: "Bot starting", message: `${server.name} is connecting` }); bot = mineflayer.createBot({ host: server.host, port: server.port, username: server.username, version: server.version === "AUTO" ? false : server.version, auth: "offline" });
  const active = { child: process, runtimeId, chat: (message: string) => bot?.chat(message), command: (command: string) => bot?.chat(command.startsWith("/") ? command : `/${command}`) }; registerRuntime(serverId, active as never);
  bot.once("login", async () => { await state("ONLINE"); await write("info", "BOT_ONLINE", "Bot connected and is online."); await publishEvent({ serverId, runtimeId, type: "BOT_ONLINE", userId: server.userId, title: "Bot online", message: `${server.name} is online` }); retries = 0; });
  bot.once("spawn", async () => { await state("ONLINE"); await write("info", "BOT_SPAWN", "Bot spawned in the world."); });
  bot.on("chat", async (username, message) => { await prisma.chatMessage.create({ data: { serverId, runtimeId, player: username, message, type: "CHAT" } }).catch(() => undefined); await write("info", "CHAT_MESSAGE", `${username}: ${message}`); await publishEvent({ serverId, runtimeId, type: "CHAT_MESSAGE", payload: { playerName: username, message } }); const config = await prisma.authConfig.findUnique({ where: { serverId }, include: { server: true } }); if (config?.enabled && config.triggerPattern && new RegExp(config.triggerPattern, "i").test(message) && config.loginCommand) { await state("AUTHENTICATING"); await publishEvent({ serverId, runtimeId, type: "AUTH_REQUIRED", userId: server.userId, title: "Authentication required", message: `${server.name} requested bot authentication` }); setTimeout(() => bot?.chat(config.loginCommand!.replace("{password}", "********")), config.delaySeconds * 1000); } });
  bot.on("playerJoined", async (player) => { await write("info", "PLAYER_JOIN", `${player.username} joined`); await publishEvent({ serverId, runtimeId, type: "PLAYER_JOIN", payload: { playerName: player.username } }); }); bot.on("playerLeft", async (player) => { await write("info", "PLAYER_LEAVE", `${player.username} left`); await publishEvent({ serverId, runtimeId, type: "PLAYER_LEAVE", payload: { playerName: player.username } }); }); bot.on("kicked", async (reason) => { await write("warning", "BOT_KICKED", `Bot kicked: ${String(reason)}`); await publishEvent({ serverId, runtimeId, type: "BOT_KICKED", userId: server.userId, title: "Bot kicked", message: `${server.name} was kicked` }); }); bot.on("error", async (error) => { await state("ERROR", error.message); await write("error", "BOT_ERROR", error.message); await publishEvent({ serverId, runtimeId, type: "BOT_ERROR", userId: server.userId, title: "Bot error", message: `${server.name}: ${error.message}` }); });
  bot.on("end", async () => { bot = undefined; const current = await prisma.botRuntime.findUnique({ where: { serverId } }); if (stopping || current?.manualStop) { await state("OFFLINE"); await publishEvent({ serverId, runtimeId, type: "BOT_OFFLINE", userId: server.userId, title: "Bot offline", message: `${server.name} is offline` }); process.exit(0); } if (!server.autoReconnect || retries >= server.maxRetries) { await state("ERROR", "Maximum reconnect attempts reached"); await publishEvent({ serverId, runtimeId, type: "BOT_ERROR", userId: server.userId, title: "Reconnect failed", message: `${server.name} reached its reconnect limit` }); process.exit(1); } retries++; const delay = Math.min(server.retryDelay * 1000 * Math.pow(2, retries - 1), 600000); await state("RECONNECTING"); await write("warning", "BOT_RECONNECT", `Reconnecting in ${Math.round(delay / 1000)} seconds.`); await publishEvent({ serverId, runtimeId, type: "BOT_RECONNECT", payload: { attempt: retries } }); setTimeout(() => run().catch(() => process.exit(1)), delay); }); const heartbeat = setInterval(async () => { const current = await prisma.botRuntime.findUnique({ where: { serverId } }); if (!current || current.runtimeId !== runtimeId) { clearInterval(heartbeat); bot?.quit(); process.exit(0); } await state(current.status); }, 15000); }
process.on("SIGTERM", async () => { stopping = true; await state("STOPPING"); await write("info", "BOT_STOP", "Worker received stop signal."); bot?.quit("Stopped by user"); setTimeout(() => process.exit(0), 1000); }); run().catch(async (error) => { await state("ERROR", String(error)); await write("error", "BOT_ERROR", String(error)); process.exit(1); });