"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Server = { id: string; name: string; host: string; port: number; edition: string; version: string; status: string; ping: number | null; runtime: { status: string } | null };
const pending = ["STARTING", "CONNECTING", "AUTHENTICATING", "RECONNECTING", "STOPPING"];
export function ServerCard({ initial }: { initial: Server }) {
  const [server, setServer] = useState(initial); const [action, setAction] = useState<string | null>(null); const [error, setError] = useState<string | null>(null);
  async function refresh() { const response = await fetch("/api/server-status", { cache: "no-store" }); if (!response.ok) return; const data = await response.json(); const current = data.servers.find((item: Server) => item.id === initial.id); if (current) setServer(current); }
  useEffect(() => { const timer = setInterval(refresh, 2000); return () => clearInterval(timer); }, []);
  async function operate(operation: "start" | "stop" | "restart") { setAction(operation); setError(null); try { const response = await fetch(`/api/servers/${server.id}/bot/${operation}`, { method: "POST" }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Operation failed"); await refresh(); } catch (e) { setError(e instanceof Error ? e.message : "Operation failed"); await refresh(); } finally { setAction(null); } }
  const status = server.runtime?.status ?? "OFFLINE"; const busy = Boolean(action) || pending.includes(status);
  return <article className="card flex flex-col gap-6 p-6 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex items-center gap-3"><div className="flex h-12 w-12 items-center justify-center rounded-xl bg-accent/15 text-accent">⛏</div><div><h2 className="truncate text-xl font-semibold">{server.name}</h2><p className="text-sm text-slate-400">{server.host}:{server.port}</p><p className="mt-1 text-xs text-slate-500">{server.edition} • {server.version}</p></div></div></div><div className="grid grid-cols-3 gap-5 text-sm"><div><p className="text-slate-500">Server</p><p className="text-emerald-300">{server.status}</p></div><div><p className="text-slate-500">Bot</p><p className={status === "ONLINE" ? "text-emerald-300" : status === "ERROR" ? "text-red-300" : "text-slate-200"}>{status}</p></div><div><p className="text-slate-500">Ping</p><p>{server.ping ?? "—"}{server.ping !== null ? "ms" : ""}</p></div></div><div className="flex flex-wrap gap-3">{status === "ONLINE" ? <><button className="btn-secondary" disabled={busy} onClick={() => operate("stop")}>{action === "stop" ? "Stopping..." : "Stop"}</button><button className="btn-secondary" disabled={busy} onClick={() => operate("restart")}>{action === "restart" ? "Restarting..." : "Restart"}</button></> : status === "ERROR" ? <button className="btn-primary" disabled={busy} onClick={() => operate("restart")}>{action === "restart" ? "Restarting..." : "Restart"}</button> : <button className="btn-primary" disabled={busy} onClick={() => operate("start")}>{action === "start" ? "Starting..." : status === "OFFLINE" ? "Start Bot" : `${status}...`}</button>}<Link className="btn-secondary" href={`/servers/${server.id}`}>Information</Link></div>{error && <p className="text-sm text-red-300 lg:absolute">{error}</p>}</article>;
}